
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    command: npm run watch
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    # volumes:
    #   - ./auth-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./auth-service/package.json
        - action: sync
          path: ./auth-service
          target: /usr/src/app
    networks:
      - microservices-network
           
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    command: npm run watch
    ports:
      - "5002:5002"
    env_file:
      - ./product-service/.env
    # volumes:
    #   - ./product-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./product-service/package.json
        - action: sync
          path: ./product-service
          target: /usr/src/app
    networks:
      - microservices-network
    depends_on:
      - auth-service


networks:
  microservices-network:
    driver: bridge