
services: 
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    command: npm run watch
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    # volumes:
    #   - ./auth-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./auth-service/package.json
        - action: sync
          path: ./auth-service
          target: /usr/src/app
    networks:
      - microservices-network
           
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    command: npm run watch
    ports:
      - "5002:5002"
    env_file:
      - ./product-service/.env
    # volumes:
    #   - ./product-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./product-service/package.json
        - action: sync
          path: ./product-service
          target: /usr/src/app
    networks:
      - microservices-network
    depends_on:
      - auth-service
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    command: npm run watch
    ports:
      - "5003:5003"
    env_file:
      - ./inventory-service/.env
    # volumes:
    #   - ./inventory-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./inventory-service/package.json
        - action: sync
          path: ./inventory-service
          target: /usr/src/app
    networks:
      - microservices-network
    depends_on:
      - auth-service
      - product-service
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    command: npm run watch
    ports:
      - "5004:5004"
    env_file:
      - ./cart-service/.env
    # volumes:
    #   - ./cart-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./cart-service/package.json
        - action: sync
          path: ./cart-service
          target: /usr/src/app
    networks:
      - microservices-network
    depends_on:
      - auth-service
      - product-service
      - inventory-service
networks:
  microservices-network:
    driver: bridge