
services:
  auth-service:
    build:
      context: ./auth-service
    command: npm run watch
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    # volumes:
    #   - ./auth-service:/usr/src/app
     
    develop:
      watch:
        - action: rebuild
          path: ./auth-service/package.json
        - action: sync
          path: ./auth-service
          target: /usr/src/app

        
