services:
  - type: web
    name: auth-service
    env: docker
    dockerfilePath: ./auth-service/Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: 'mongodb+srv://gurudaspranavam007:h4WW6O5NyBuHL84j@cluster0.1ov8q.mongodb.net/e-commerce?retryWrites=true&w=majority&appName=Cluster0'
      - key: FROM_MAIL_ID
        value: contact.ashflix@gmail.com
      - key: FROM_MAIL_PASSWORD
        value: hjsvopggvshjmuwt
      - key: JWT_SECRET
        value: Mxc04sd2FUbcbNfArP9Lrha4ijhBZ8JXCnQWKEcwRMU=

  - type: web
    name: product-service
    env: docker
    dockerfilePath: ./product-service/Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5002
      - key: MONGODB_URI
        value: 'mongodb+srv://gurudaspranavam007:h4WW6O5NyBuHL84j@cluster0.1ov8q.mongodb.net/e-commerce?retryWrites=true&w=majority&appName=Cluster0'
      - key: JWT_SECRET
        value: Mxc04sd2FUbcbNfArP9Lrha4ijhBZ8JXCnQWKEcwRMU=
      - key: CLOUD_NAME
        value: dn4kcza7g
      - key: API_KEY
        value: 519873683241892
      - key: API_SECRET
        value: CSXU-RnW2p_SCpPzyZilkg1Juuc
      - key: INVENTORY_SERVICE_URL
        value: http://inventory-service:5003

  - type: web
    name: inventory-service
    env: docker
    dockerfilePath: ./inventory-service/Dockerfile
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5003
      - key: MONGODB_URI
        value: 'mongodb+srv://gurudaspranavam007:h4WW6O5NyBuHL84j@cluster0.1ov8q.mongodb.net/e-commerce?retryWrites=true&w=majority&appName=Cluster0'
      - key: JWT_SECRET
        value: Mxc04sd2FUbcbNfArP9Lrha4ijhBZ8JXCnQWKEcwRMU=
